[2022-10-08T12:02:51.574+0000] {processor.py:156} INFO - Started process (PID=178) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:02:51.575+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:02:51.575+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:02:51.575+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:02:51.578+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:02:51.577+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:02:51.578+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:02:51.593+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:03:21.687+0000] {processor.py:156} INFO - Started process (PID=211) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:03:21.688+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:03:21.688+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:03:21.688+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:03:21.690+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:03:21.690+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:03:21.691+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:03:21.707+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:03:51.800+0000] {processor.py:156} INFO - Started process (PID=243) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:03:51.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:03:51.801+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:03:51.801+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:03:51.803+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:03:51.803+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:03:51.804+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:03:51.819+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:04:21.912+0000] {processor.py:156} INFO - Started process (PID=266) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:04:21.913+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:04:21.913+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:04:21.913+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:04:21.915+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:04:21.914+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:04:21.915+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:04:21.933+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:04:52.026+0000] {processor.py:156} INFO - Started process (PID=298) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:04:52.027+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:04:52.027+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:04:52.027+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:04:52.029+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:04:52.029+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:04:52.030+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:04:52.046+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:05:22.138+0000] {processor.py:156} INFO - Started process (PID=330) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:05:22.139+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:05:22.140+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:05:22.140+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:05:22.141+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:05:22.141+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:05:22.142+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:05:22.158+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:05:52.252+0000] {processor.py:156} INFO - Started process (PID=362) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:05:52.252+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:05:52.253+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:05:52.253+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:05:52.255+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:05:52.254+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:05:52.255+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:05:52.271+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:06:22.360+0000] {processor.py:156} INFO - Started process (PID=385) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:06:22.360+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:06:22.361+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:06:22.361+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:06:22.363+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:06:22.362+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:06:22.363+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:06:22.379+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:06:52.473+0000] {processor.py:156} INFO - Started process (PID=417) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:06:52.474+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:06:52.474+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:06:52.474+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:06:52.476+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:06:52.475+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:06:52.476+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:06:52.493+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:07:22.583+0000] {processor.py:156} INFO - Started process (PID=449) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:07:22.584+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:07:22.585+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:07:22.584+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:07:22.586+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:07:22.586+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:07:22.587+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:07:22.603+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:07:52.706+0000] {processor.py:156} INFO - Started process (PID=472) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:07:52.706+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:07:52.707+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:07:52.707+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:07:52.709+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:07:52.708+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:07:52.709+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:07:52.811+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.108 seconds
[2022-10-08T12:08:23.002+0000] {processor.py:156} INFO - Started process (PID=504) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:08:23.003+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:08:23.003+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:08:23.003+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:08:23.005+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:08:23.005+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:08:23.006+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:08:23.023+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:08:53.108+0000] {processor.py:156} INFO - Started process (PID=536) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:08:53.109+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:08:53.109+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:08:53.109+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:08:53.111+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:08:53.111+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:08:53.112+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:08:53.127+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:09:23.220+0000] {processor.py:156} INFO - Started process (PID=568) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:09:23.221+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:09:23.221+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:09:23.221+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:09:23.223+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:09:23.223+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:09:23.224+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:09:23.240+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:09:53.336+0000] {processor.py:156} INFO - Started process (PID=591) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:09:53.337+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:09:53.338+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:09:53.338+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:09:53.340+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:09:53.339+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:09:53.340+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:09:53.357+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:10:23.452+0000] {processor.py:156} INFO - Started process (PID=623) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:10:23.452+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:10:23.453+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:10:23.453+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:10:23.455+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:10:23.454+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:10:23.455+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:10:23.472+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:10:53.569+0000] {processor.py:156} INFO - Started process (PID=655) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:10:53.570+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:10:53.570+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:10:53.570+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:10:53.573+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:10:53.572+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:10:53.573+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:10:53.590+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:11:23.682+0000] {processor.py:156} INFO - Started process (PID=687) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:11:23.682+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:11:23.683+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:11:23.683+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:11:23.685+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:11:23.684+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:11:23.685+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:11:23.701+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:11:53.794+0000] {processor.py:156} INFO - Started process (PID=710) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:11:53.795+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:11:53.796+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:11:53.795+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:11:53.798+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:11:53.797+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:11:53.798+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:11:53.814+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
